name: ModPack
version: '${project.version}'
main: me.sk.modpack.Main
api-version: 1.19

commands:
  eat:
    description: Puts players foodbar to max (20)
  heal:
    description: heal yourself
  god:
    description: become invulnerable
  home:
    description: Warp to location
  sethome:
    description: set a warp to location
  delhome:
    description: delete the warp